FROM node:22-bookworm-slim AS base
WORKDIR /app
ENV NEXT_TELEMETRY_DISABLED=1

FROM base AS dependencies
COPY package.json package-lock.json ./
RUN npm ci --legacy-peer-deps

FROM base AS builder
COPY --from=dependencies /app/node_modules ./node_modules
COPY . .
ARG NEXT_PUBLIC_SITE_URL
ARG NEXT_PUBLIC_SITE_NAME
ARG NEXT_PUBLIC_SITE_SHORT_NAME
ARG NEXT_PUBLIC_ORGANIZATION_NAME
ARG NEXT_PUBLIC_DEFAULT_LOCALE
ARG NEXT_PUBLIC_DEFAULT_DIRECTION
ARG NEXT_PUBLIC_LOGO_PATH
ARG NEXT_PUBLIC_FAVICON_PATH
ARG NEXT_PUBLIC_APPLE_TOUCH_ICON_PATH
ARG NEXT_PUBLIC_PWA_ICON_192_PATH
ARG NEXT_PUBLIC_PWA_ICON_512_PATH
ARG NEXT_PUBLIC_PWA_MASKABLE_ICON_PATH
ARG NEXT_PUBLIC_OG_IMAGE_PATH
ARG NEXT_PUBLIC_SUPPLICATIONS_PDF_PATH
ARG NEXT_PUBLIC_SEO_TITLE
ARG NEXT_PUBLIC_SEO_DESCRIPTION
ARG NEXT_PUBLIC_SEO_KEYWORDS
ARG NEXT_PUBLIC_SOCIAL_HANDLE
ARG NEXT_PUBLIC_MEMORIAL_LEGAL_NAME
ARG NEXT_PUBLIC_MEMORIAL_NAME
ARG NEXT_PUBLIC_MEMORIAL_ALTERNATE_NAME
ARG NEXT_PUBLIC_MEMORIAL_DEATH_DATE
ARG NEXT_PUBLIC_MEMORIAL_DATE_TEXT
ARG NEXT_PUBLIC_HERO_DESCRIPTION
ARG NEXT_PUBLIC_FOOTER_CHARITY_TEXT
ARG NEXT_PUBLIC_DONATION_URL
ARG NEXT_PUBLIC_QURAN_PLAYLIST_ID
ARG NEXT_PUBLIC_QURAN_PLAYLIST_START_VIDEO_ID
ARG NEXT_PUBLIC_FAVORITE_RECITER_PLAYLIST_ID
ARG NEXT_PUBLIC_FAVORITE_RECITER_START_VIDEO_ID
ARG NEXT_PUBLIC_ISLAMIC_CHANT_VIDEO_ID
ARG NEXT_PUBLIC_SOCIAL_LINKS
ARG NEXT_PUBLIC_FALLBACK_LATITUDE
ARG NEXT_PUBLIC_FALLBACK_LONGITUDE
ARG NEXT_PUBLIC_FALLBACK_CITY
ARG NEXT_PUBLIC_FALLBACK_COUNTRY
ARG NEXT_PUBLIC_FALLBACK_COUNTRY_CODE
ARG NEXT_PUBLIC_FALLBACK_FAJR
ARG NEXT_PUBLIC_FALLBACK_SUNRISE
ARG NEXT_PUBLIC_FALLBACK_DHUHR
ARG NEXT_PUBLIC_FALLBACK_ASR
ARG NEXT_PUBLIC_FALLBACK_MAGHRIB
ARG NEXT_PUBLIC_FALLBACK_ISHA
ARG NEXT_PUBLIC_COLOR_BRAND
ARG NEXT_PUBLIC_COLOR_ACCENT
ARG NEXT_PUBLIC_COLOR_LINK
ARG NEXT_PUBLIC_COLOR_BACKGROUND_DARK
ARG NEXT_PUBLIC_COLOR_BACKGROUND_DARK_SECONDARY
ARG NEXT_PUBLIC_COLOR_BACKGROUND_DARK_ACCENT
ARG NEXT_PUBLIC_COLOR_BACKGROUND_LIGHT
ARG NEXT_PUBLIC_COLOR_BACKGROUND_LIGHT_SECONDARY
ARG NEXT_PUBLIC_COLOR_BACKGROUND_LIGHT_ACCENT
ARG NEXT_PUBLIC_PWA_ID
ARG NEXT_PUBLIC_PWA_START_URL
ARG NEXT_PUBLIC_ENABLE_VERCEL_ANALYTICS
ARG NEXT_PUBLIC_VAPID_PUBLIC_KEY
ENV NEXT_PUBLIC_SITE_URL=$NEXT_PUBLIC_SITE_URL \
    NEXT_PUBLIC_SITE_NAME=$NEXT_PUBLIC_SITE_NAME \
    NEXT_PUBLIC_SITE_SHORT_NAME=$NEXT_PUBLIC_SITE_SHORT_NAME \
    NEXT_PUBLIC_ORGANIZATION_NAME=$NEXT_PUBLIC_ORGANIZATION_NAME \
    NEXT_PUBLIC_DEFAULT_LOCALE=$NEXT_PUBLIC_DEFAULT_LOCALE \
    NEXT_PUBLIC_DEFAULT_DIRECTION=$NEXT_PUBLIC_DEFAULT_DIRECTION \
    NEXT_PUBLIC_LOGO_PATH=$NEXT_PUBLIC_LOGO_PATH \
    NEXT_PUBLIC_FAVICON_PATH=$NEXT_PUBLIC_FAVICON_PATH \
    NEXT_PUBLIC_APPLE_TOUCH_ICON_PATH=$NEXT_PUBLIC_APPLE_TOUCH_ICON_PATH \
    NEXT_PUBLIC_PWA_ICON_192_PATH=$NEXT_PUBLIC_PWA_ICON_192_PATH \
    NEXT_PUBLIC_PWA_ICON_512_PATH=$NEXT_PUBLIC_PWA_ICON_512_PATH \
    NEXT_PUBLIC_PWA_MASKABLE_ICON_PATH=$NEXT_PUBLIC_PWA_MASKABLE_ICON_PATH \
    NEXT_PUBLIC_OG_IMAGE_PATH=$NEXT_PUBLIC_OG_IMAGE_PATH \
    NEXT_PUBLIC_SUPPLICATIONS_PDF_PATH=$NEXT_PUBLIC_SUPPLICATIONS_PDF_PATH \
    NEXT_PUBLIC_SEO_TITLE=$NEXT_PUBLIC_SEO_TITLE \
    NEXT_PUBLIC_SEO_DESCRIPTION=$NEXT_PUBLIC_SEO_DESCRIPTION \
    NEXT_PUBLIC_SEO_KEYWORDS=$NEXT_PUBLIC_SEO_KEYWORDS \
    NEXT_PUBLIC_SOCIAL_HANDLE=$NEXT_PUBLIC_SOCIAL_HANDLE \
    NEXT_PUBLIC_MEMORIAL_LEGAL_NAME=$NEXT_PUBLIC_MEMORIAL_LEGAL_NAME \
    NEXT_PUBLIC_MEMORIAL_NAME=$NEXT_PUBLIC_MEMORIAL_NAME \
    NEXT_PUBLIC_MEMORIAL_ALTERNATE_NAME=$NEXT_PUBLIC_MEMORIAL_ALTERNATE_NAME \
    NEXT_PUBLIC_MEMORIAL_DEATH_DATE=$NEXT_PUBLIC_MEMORIAL_DEATH_DATE \
    NEXT_PUBLIC_MEMORIAL_DATE_TEXT=$NEXT_PUBLIC_MEMORIAL_DATE_TEXT \
    NEXT_PUBLIC_HERO_DESCRIPTION=$NEXT_PUBLIC_HERO_DESCRIPTION \
    NEXT_PUBLIC_FOOTER_CHARITY_TEXT=$NEXT_PUBLIC_FOOTER_CHARITY_TEXT \
    NEXT_PUBLIC_DONATION_URL=$NEXT_PUBLIC_DONATION_URL \
    NEXT_PUBLIC_QURAN_PLAYLIST_ID=$NEXT_PUBLIC_QURAN_PLAYLIST_ID \
    NEXT_PUBLIC_QURAN_PLAYLIST_START_VIDEO_ID=$NEXT_PUBLIC_QURAN_PLAYLIST_START_VIDEO_ID \
    NEXT_PUBLIC_FAVORITE_RECITER_PLAYLIST_ID=$NEXT_PUBLIC_FAVORITE_RECITER_PLAYLIST_ID \
    NEXT_PUBLIC_FAVORITE_RECITER_START_VIDEO_ID=$NEXT_PUBLIC_FAVORITE_RECITER_START_VIDEO_ID \
    NEXT_PUBLIC_ISLAMIC_CHANT_VIDEO_ID=$NEXT_PUBLIC_ISLAMIC_CHANT_VIDEO_ID \
    NEXT_PUBLIC_SOCIAL_LINKS=$NEXT_PUBLIC_SOCIAL_LINKS \
    NEXT_PUBLIC_FALLBACK_LATITUDE=$NEXT_PUBLIC_FALLBACK_LATITUDE \
    NEXT_PUBLIC_FALLBACK_LONGITUDE=$NEXT_PUBLIC_FALLBACK_LONGITUDE \
    NEXT_PUBLIC_FALLBACK_CITY=$NEXT_PUBLIC_FALLBACK_CITY \
    NEXT_PUBLIC_FALLBACK_COUNTRY=$NEXT_PUBLIC_FALLBACK_COUNTRY \
    NEXT_PUBLIC_FALLBACK_COUNTRY_CODE=$NEXT_PUBLIC_FALLBACK_COUNTRY_CODE \
    NEXT_PUBLIC_FALLBACK_FAJR=$NEXT_PUBLIC_FALLBACK_FAJR \
    NEXT_PUBLIC_FALLBACK_SUNRISE=$NEXT_PUBLIC_FALLBACK_SUNRISE \
    NEXT_PUBLIC_FALLBACK_DHUHR=$NEXT_PUBLIC_FALLBACK_DHUHR \
    NEXT_PUBLIC_FALLBACK_ASR=$NEXT_PUBLIC_FALLBACK_ASR \
    NEXT_PUBLIC_FALLBACK_MAGHRIB=$NEXT_PUBLIC_FALLBACK_MAGHRIB \
    NEXT_PUBLIC_FALLBACK_ISHA=$NEXT_PUBLIC_FALLBACK_ISHA \
    NEXT_PUBLIC_COLOR_BRAND=$NEXT_PUBLIC_COLOR_BRAND \
    NEXT_PUBLIC_COLOR_ACCENT=$NEXT_PUBLIC_COLOR_ACCENT \
    NEXT_PUBLIC_COLOR_LINK=$NEXT_PUBLIC_COLOR_LINK \
    NEXT_PUBLIC_COLOR_BACKGROUND_DARK=$NEXT_PUBLIC_COLOR_BACKGROUND_DARK \
    NEXT_PUBLIC_COLOR_BACKGROUND_DARK_SECONDARY=$NEXT_PUBLIC_COLOR_BACKGROUND_DARK_SECONDARY \
    NEXT_PUBLIC_COLOR_BACKGROUND_DARK_ACCENT=$NEXT_PUBLIC_COLOR_BACKGROUND_DARK_ACCENT \
    NEXT_PUBLIC_COLOR_BACKGROUND_LIGHT=$NEXT_PUBLIC_COLOR_BACKGROUND_LIGHT \
    NEXT_PUBLIC_COLOR_BACKGROUND_LIGHT_SECONDARY=$NEXT_PUBLIC_COLOR_BACKGROUND_LIGHT_SECONDARY \
    NEXT_PUBLIC_COLOR_BACKGROUND_LIGHT_ACCENT=$NEXT_PUBLIC_COLOR_BACKGROUND_LIGHT_ACCENT \
    NEXT_PUBLIC_PWA_ID=$NEXT_PUBLIC_PWA_ID \
    NEXT_PUBLIC_PWA_START_URL=$NEXT_PUBLIC_PWA_START_URL \
    NEXT_PUBLIC_ENABLE_VERCEL_ANALYTICS=$NEXT_PUBLIC_ENABLE_VERCEL_ANALYTICS \
    NEXT_PUBLIC_VAPID_PUBLIC_KEY=$NEXT_PUBLIC_VAPID_PUBLIC_KEY
RUN npm run build

FROM node:22-bookworm-slim AS runner
WORKDIR /app
ENV NODE_ENV=production \
    NEXT_TELEMETRY_DISABLED=1 \
    HOSTNAME=0.0.0.0 \
    PORT=3000

RUN groupadd --system --gid 1001 nodejs \
    && useradd --system --uid 1001 --gid nodejs nextjs

COPY --from=builder --chown=nextjs:nodejs /app/public ./public
COPY --from=builder --chown=nextjs:nodejs /app/.next/standalone ./
COPY --from=builder --chown=nextjs:nodejs /app/.next/static ./.next/static

USER nextjs
EXPOSE 3000
HEALTHCHECK --interval=30s --timeout=5s --start-period=20s --retries=3 \
  CMD ["node", "-e", "fetch('http://127.0.0.1:3000/health').then(r=>{if(!r.ok)process.exit(1)}).catch(()=>process.exit(1))"]
CMD ["node", "server.js"]
