services:
  - type: web
    name: ongoing-charity
    runtime: docker
    dockerfilePath: ./Dockerfile
    dockerContext: .
    healthCheckPath: /health
    autoDeployTrigger: 'off'
    envVars:
      - key: NEXT_TELEMETRY_DISABLED
        value: "1"
      - key: NEXT_PUBLIC_SITE_URL
        sync: false
      - key: NEXT_PUBLIC_SITE_NAME
        sync: false
      - key: NEXT_PUBLIC_SITE_SHORT_NAME
        sync: false
      - key: NEXT_PUBLIC_ORGANIZATION_NAME
        sync: false
      - key: NEXT_PUBLIC_MEMORIAL_NAME
        sync: false
      - key: NEXT_PUBLIC_MEMORIAL_LEGAL_NAME
        sync: false
      - key: NEXT_PUBLIC_MEMORIAL_ALTERNATE_NAME
        sync: false
      - key: NEXT_PUBLIC_MEMORIAL_DEATH_DATE
        sync: false
      - key: NEXT_PUBLIC_DONATION_URL
        sync: false
      - key: NEXT_PUBLIC_COLOR_BRAND
        sync: false
      - key: NEXT_PUBLIC_COLOR_ACCENT
        sync: false
      - key: NEXT_PUBLIC_COLOR_LINK
        sync: false
      - key: NEXT_PUBLIC_DEFAULT_LOCALE
        sync: false
      - key: NEXT_PUBLIC_DEFAULT_DIRECTION
        sync: false
