import { SUPPORTED_LOCALES, type SupportedLocale } from "@/config/site";
import { STORY_SLUGS, type StoryPdfLocale, type StorySlug } from "./types";

/**
 * Locales that have a dedicated PDF on disk under `/stories/{slug}/{locale}.pdf`.
 * Arabic originals always exist; other locales are generated by
 * `npm run generate:story-pdfs`. Missing locales fall back to `ar.pdf`.
 */
export const STORY_PDF_LOCALES = {
  "al-khidr-or-destiny": SUPPORTED_LOCALES,
  "ash-shura": SUPPORTED_LOCALES,
  "al-jinn": SUPPORTED_LOCALES,
  "an-naml": SUPPORTED_LOCALES,
} as const satisfies Record<StorySlug, readonly StoryPdfLocale[]>;

void STORY_SLUGS;

export function storyPdfPublicPath(slug: StorySlug, locale: StoryPdfLocale): string {
  return `/stories/${slug}/${locale}.pdf`;
}

/** True when the UI locale has no dedicated PDF and must use the Arabic original. */
export function isStoryPdfFallback(slug: StorySlug, locale: SupportedLocale): boolean {
  const available = STORY_PDF_LOCALES[slug] ?? ["ar"];
  return !available.includes(locale as StoryPdfLocale);
}

/**
 * Resolve a public PDF URL for a story + UI locale.
 * Prefers `/stories/{slug}/{locale}.pdf` when present; otherwise falls back to `ar.pdf`.
 * Never returns a path that would 404 for a supported UI locale.
 */
export function resolveStoryPdf(slug: StorySlug, locale: SupportedLocale): string {
  const available = STORY_PDF_LOCALES[slug] ?? ["ar"];
  const pdfLocale = available.includes(locale as StoryPdfLocale)
    ? (locale as StoryPdfLocale)
    : "ar";
  return storyPdfPublicPath(slug, pdfLocale);
}
